package io.github.secondflight.util;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Words {
	public static List<String> getList() {
		String s = ("Vitriolize mudlark kubelik pretranscribe canonize aubrey poloist overhearer monotonic dozily integrationist inculcator jugoslav carotinoid Gynophoric cowry tattletale cyzicus malign zoolatry logographic maulmain overtly diyarbakir vilifying criminal amadeo cutover Hypermetamorphosis lingcod nonhumanist mutuel substriated gooding peccantly unpotting deafen cunctatorship understrata pseudohypertrophic windingness scabious Cleping insectarium ungeneralized exoperidium nonconvective loaded grump perimedes diapausing jambos etymologizable jequirity unhasted infantryman Coercer phlegmless jiva octangular sprayer tiswin upheaver nip normalise jig unmelancholy consortial trunks pulu Parliamentarism washing telepathically anatolic ascetic cyril authoress forme mordvinian mush damaskeen ochrea frozenness defilade Sulphurise humoresquely urinous unshimmering christy fruitiness matapan bedaub injurable conglutinate vesuvianite glacier longheadedness cockatrice Insobriety misappellation trimetrogon stromateid nonbuoyancy gallbladder groundling supercatholically drug socratic contradictor predecide paravent Lunar telepathize untranscribable intertidal battalion nonconfining culiac driftfishes siphonlike cainitic samuel precautious granados dynamism Vanadinite bilboes topic feu bernadette corniced insolvency deleted unpadlocked inwrought cymbalom burley preconsolidated annihilate Incrassating bransle autocephaly aphoristically gourmand jackboxes fingered prodigiously fathead revising unswear brandy paraffinize neumayer Barrs apemosyne preservation testifying corymb agglomeration ileac starveling jayhawker curser revisal aurification copycat peckinpah Swallowwort journalizing canceration haboub chattable bureaucrat affreightment learned thrusting titanosaur looie vavasour lithuanian eggcup Idumea repurified coaxal defamed hybridizer regamble esperantist saturated cornstone godding quenelle gynaecocrat inheritableness quetta Enkephalin unoxidised diogenic himeji nereis val lang centrifuged comrade wildflower suborder intense muggy innings Outsat antilogistically demoralizer motored aggravatingly montpelier sudationes conglomerated diazomethane exoderm geodetical proselytise untoasted oversettlement Superguarantee globigerina unhorse pentastylos klepht nonalkaloidal richlands ceroma bejeweled cytotrophoblastic idiochromatic freezingly cocoon presession Subdivided unprompt evros vie chitchat acknowledge unblinkingly tomcatting selfheal emmelene gayal unsombre pastime episiotomy Fonda unspectacular literalize unquizzical controvertist murine saunder regress lignify draughtiness equipoise uni anelace jerseyville Dekko gnu inestimability calibrate collotypy noninterchangeable stalactite blasted humdrum splicing conductivity layover strongylosis pickaxed");
		
		return new ArrayList<String>(Arrays.asList(s.split(" ")));
	}
}
